Disambiguate format_to
For now we are using fmt::format everywhere, so we should use
fmt::format_to as well.

Otherwise with C++20 we may get an error for an ambiguous definition, as
std::format_to may shadow fmt::format_to, for example with gcc the error
may look like this:

```
error: call of overloaded ‘format_to(fmt::v8::basic_format_context<fmt::v8::appender, char>::iterator, const char [9], float, float)’ is ambiguous
(...)
candidate: ‘OutputIt fmt::v8::format_to(OutputIt, format_string<T ...>, T&& ...)
(...)
candidate: ‘_Out std::format_to(_Out, format_string<_Args ...>, _Args&& ...)
```

Signed-off-by: Magnus Groß <magnus.gross@kdab.com>